version: 0.2

phases:
  install:
    runtime-versions:
      ruby: 2.6
  pre_build:
    commands:
      - gem install bundler:2.0.2
      - make install
  build:
    commands:
      - echo ">>>>>>>> Running the tests..."
      - make test
